site_name: Mine Design Help Guide
site_url: https://example.com/
nav:
    - Quick Reference Guide: quickreferenceguide.md
    - Chapter 1 Introduction: index.md
    - Chapter 2 User Registration: registration.md
    - Chapter 3 Setting Up a Project: projectsetup.md
    - Chapter 4 Mine Design Core Module: MineDesignCoreModule.md
    - Chapter 5 Opencontour Heap Leach Stacking: OpencontourHeapLeachStacking.md
theme: 
    name: material
    palette:
        primary: green
